DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS family;
DROP TABLE IF EXISTS apidata;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE family (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ship TEXT NOT NULL,
  famname TEXT NOT NULL,
  addres TEXT NOT NULL,
  filepath TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE apidata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  date DATE DEFAULT CURRENT_TIMESTAMP,
  action TEXT NOT NULL,
  place TEXT NOT NULL,
  money INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
